addpath('/media/eleyng/TOSHIBA EXT/Learning/PAWN/PAWN')
addpath('/home/eleyng/Documents/subl/learning/cs229project')
addpath('/home/eleyng/Documents/subl/learning')
addpath('/media/eleyng/TOSHIBA EXT/Learning/PAWN/PAWN/10_19')
load('/media/eleyng/TOSHIBA EXT/Learning/PAWN/PAWN/10_19/pawned.mat')